// shellmods - a standalone host for Windhawk mods.
//
// Internal runtime shared by the shim translation units. Nothing here is
// visible to mod sources: mods see only the three vendored upstream headers in
// shim/include, and every Wh_* call they make funnels through the
// InternalWh_* boundary implemented across shim/src.
#pragma once

#include <windows.h>

#include <string>
#include <vector>

namespace shim {

// ---------------------------------------------------------------------------
// Process-wide state, established once by Startup().
// ---------------------------------------------------------------------------

// Mod identity, baked in per-project via /D WH_MOD_ID and /D WH_MOD_VERSION.
extern std::wstring g_modId;

// dist/ root: the parent of the directory holding this mod DLL. Anchors
// shellmods.ini, offsets\, storage\, shellmods.log and the DISABLE kill switch.
extern std::wstring g_baseDir;

extern bool g_logEnabled;

// Paths derived from g_baseDir.
std::wstring IniPath();
std::wstring LogPath();
std::wstring OffsetsDir();
std::wstring StorageDir();
std::wstring DisableFlagPath();

// Resolves g_baseDir from thisModule and reads the [shellmods] section.
// Returns false when the mod must not run at all: the kill switch is present,
// Windows is in safe mode, or the layout on disk is unusable.
bool Startup(HMODULE thisModule);

// Two levels, deliberately:
//   Logf      - shim diagnostics. Always written. Low volume (a handful of
//               lines per injection) and it carries the things you cannot
//               afford to have hidden behind a flag, above all "these offsets
//               are stale, refusing to hook".
//   Wh_Log    - the mods' own tracing, gated on [shellmods] Log. High volume:
//               every hook entry logs, which is roughly a megabyte a minute.
void Log(PCWSTR format, va_list args);
void Logf(PCWSTR format, ...);

// Re-reads the [shellmods] section. Called at startup and on every INI change,
// so toggling Log takes effect without restarting Explorer.
void ReloadGlobalSettings();

// ---------------------------------------------------------------------------
// Hook engine (shim_hooks.cpp), backed by MinHook.
// ---------------------------------------------------------------------------

// Wh_SetFunctionHook semantics: register, do not activate. Activation happens
// in ApplyHookOperations, mirroring how Windhawk defers to a single
// MH_ApplyQueued after Wh_ModInit returns.
bool HookRegister(void* target, void* detour, void** original);
bool HookUnregister(void* target);
bool ApplyHookOperations();

// Disables every hook this DLL installed. Used on explicit unload only.
void HookShutdownAll();

// ---------------------------------------------------------------------------
// Symbols (shim_symbols.cpp).
// ---------------------------------------------------------------------------

// Looks up one symbol by its Windhawk-style undecorated name in the .sym file
// generated by symgen for `module`. Returns nullptr when absent.
void* ResolveSymbol(HMODULE module, const WCHAR* name, size_t nameLength);

// True when the .sym file for `module` exists AND its recorded fingerprint
// matches the module currently mapped in this process. A mismatch means a
// Windows update moved things under us, so every symbol hook must be refused
// rather than applied at a stale address.
bool SymbolsUsable(HMODULE module);

// ---------------------------------------------------------------------------
// Mod lifecycle.
// ---------------------------------------------------------------------------

// Windhawk discovers the five mod callbacks as DLL exports and tolerates any of
// them being absent. We have no engine doing that lookup, so instead each mod
// project supplies one small glue file naming exactly the callbacks its own
// source defines, leaving the rest null. That keeps the decision in source the
// compiler checks, rather than in a .def file that fails at link time when
// upstream adds or drops a callback.
struct ModCallbacks {
    BOOL (*init)();
    void (*afterInit)();
    void (*beforeUninit)();
    void (*uninit)();
    // Windhawk accepts two shapes for the settings callback and calls whichever
    // the mod exported. Of our three mods, filesizes uses the second form to ask
    // for a full reload. At most one of these should be set.
    void (*settingsChanged)();
    BOOL (*settingsChangedReload)(BOOL* reload);
};

}  // namespace shim

// Both defined by mods/<mod>/mod_glue.cpp. The shim is one static library
// shared by all three mods, so the mod's identity arrives at link time rather
// than as a compile-time define.
extern const shim::ModCallbacks g_shellModsCallbacks;
extern const wchar_t* const g_shellModsModId;
