#!/usr/bin/env python3
"""Generate symreq\\<mod>.symreq from the ported mod sources.

symgen needs to know which symbol names to resolve. Those names live in the mod
sources as raw string literals inside SYMBOL_HOOK arrays -- but those arrays are
built inside functions, behind runtime conditionals on the Windows build, so
there is no way to enumerate "the symbols this mod will ask for" statically.

So we deliberately over-collect: every LR"(...)" literal in the source becomes a
request. That is a superset of what any code path can ask for. Over-collection
costs nothing -- a name that is not a symbol, or belongs to a different module,
simply does not resolve -- and it means a mod update that adds a hook is picked
up by re-running this script rather than by hand-maintaining a list.

The module list per mod cannot be derived the same way (the sources name modules
via GetModuleHandle/LoadLibraryEx calls scattered through the hook setup), so it
is recorded here explicitly, with the source line that justifies it.

    python tools\\extract_symreq.py
"""

from __future__ import annotations

import io
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

# Modules each mod resolves symbols in. Taskbar names several alternatives
# because the Windows 11 taskbar has been reorganised across builds; symgen
# skips the ones absent on a given machine.
MODS = {
    "taskbar": {
        "id": "taskbar-icon-size",
        "modules": [
            ("Taskbar.View.dll", "GetTaskbarViewDllModule"),
            ("ExplorerExtensions.dll", "GetTaskbarViewDllModule fallback"),
            ("SystemTray.dll", "GetSystemTrayDllModule"),
            ("SearchUx.UI.dll", "GetSearchUxUiDllModule"),
            ("taskbar.dll", "HookTaskbarDllSymbols"),
        ],
    },
    "ctxmenu": {
        "id": "explorer-context-menu-classic",
        "modules": [
            ("explorerframe.dll", "HookExplorerFrameSymbols"),
        ],
    },
    "filesizes": {
        "id": "explorer-details-better-file-sizes",
        "modules": [
            ("windows.storage.dll", "HookWindowsStorageSymbols"),
        ],
    },
}

# Raw literals that are plainly not symbol names. Shell column specifications
# share the LR"(...)" spelling but describe a details view, not a function.
NOT_A_SYMBOL = re.compile(r"^(prop:|Local\\|Global\\)")


def main() -> int:
    # dist/ so the files ship: the release archive is a copy of dist/, and
    # symgen resolves symreq\ relative to its own directory.
    out_dir = ROOT / "dist" / "symreq"
    out_dir.mkdir(parents=True, exist_ok=True)

    for folder, spec in MODS.items():
        src = ROOT / "mods" / folder / f"{folder}.wh.cpp"
        if not src.exists():
            raise SystemExit(f"missing {src} -- run tools/port_mods.py first")

        text = src.read_text(encoding="utf-8")
        literals = re.findall(r'LR"\((.*?)\)"', text, re.DOTALL)

        names: list[str] = []
        seen = set()
        for literal in literals:
            if "\n" in literal or NOT_A_SYMBOL.match(literal):
                continue
            if literal in seen:
                continue
            seen.add(literal)
            names.append(literal)

        lines = [
            f"# {spec['id']}",
            "# Generated by tools/extract_symreq.py -- do not edit by hand.",
            "# Every LR\"(...)\" literal from the mod source, which is a superset",
            "# of the symbols any code path can request. Names that are not",
            "# symbols, or belong to another module, simply do not resolve.",
            "",
        ]
        for module, why in spec["modules"]:
            lines.append(f"!module {module}    # {why}")
        lines.append("")
        lines.extend(names)
        lines.append("")

        out = out_dir / f"{folder}.symreq"
        with io.open(out, "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(lines))

        print(f"{folder:10s} {len(spec['modules'])} module(s), "
              f"{len(names)} name(s) -> {out.relative_to(ROOT)}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
